export const CATEGORIES = [
  "All",
  "Food & Nutrition",
  "Housing",
  "Healthcare",
  "Refugee & Immigration",
  "Legal Aid",
  "Mental Health",
  "Employment",
  "Youth & Family",
];

export const RESOURCES = [
  // FOOD & NUTRITION
  {
    name: "Mohawk Valley Community Action Agency",
    category: "Food & Nutrition",
    description: "Emergency food pantry, SNAP application assistance, and utility assistance for low-income Oneida County residents.",
    address: "270 Bleecker St, Utica, NY 13501",
    phone: "(315) 272-6200",
    website: "https://www.mvcaa.com",
    hours: "Mon–Fri 8:30am–4:30pm",
    tags: ["food pantry", "SNAP", "emergency assistance"],
  },
  {
    name: "Rescue Mission of Utica",
    category: "Food & Nutrition",
    description: "Free meals, food pantry, emergency shelter for men, and addiction stabilization services. Over 130 years serving Utica.",
    address: "293 Genesee St, Utica, NY 13501",
    phone: "(315) 735-1645",
    website: "https://uticamission.org",
    hours: "Daily — meals at breakfast, lunch & dinner",
    tags: ["free meals", "food pantry", "shelter", "addiction"],
  },
  {
    name: "Catholic Charities of Oneida & Madison Counties",
    category: "Food & Nutrition",
    description: "Food pantry, emergency financial assistance, counseling, and social services regardless of religious affiliation.",
    address: "1408 Genesee St, Utica, NY 13501",
    phone: "(315) 724-2158",
    website: "https://www.catholiccharitiesom.org",
    hours: "Mon–Fri 9am–4pm",
    tags: ["food pantry", "emergency assistance", "social services", "counseling"],
  },
  {
    name: "Regional Food Bank of Northeastern NY — Utica",
    category: "Food & Nutrition",
    description: "Regional food bank distributing to 1,000+ partner agencies across 23 counties. Find a local pantry via their site.",
    address: "Serves Oneida County via partner network",
    phone: "(518) 786-3691",
    website: "https://www.regionalfoodbank.net",
    hours: "Partner locator available online 24/7",
    tags: ["food bank", "pantry locator", "SNAP"],
  },

  // HOUSING
  {
    name: "Utica Municipal Housing Authority",
    category: "Housing",
    description: "Public housing and Section 8 Housing Choice Voucher program for income-qualifying Utica residents.",
    address: "509 Elizabeth St, Utica, NY 13501",
    phone: "(315) 732-4391",
    website: "https://www.uticaha.org",
    hours: "Mon–Fri 8am–4pm",
    tags: ["Section 8", "public housing", "voucher"],
  },
  {
    name: "The Neighborhood Center — Housing & Family Services",
    category: "Housing",
    description: "Homelessness prevention, rental assistance, housing counseling, and behavioral health services for Oneida County residents.",
    address: "624 Elizabeth St, Utica, NY 13501",
    phone: "(315) 272-2600",
    website: "https://www.neighborhoodctr.org",
    hours: "Mon–Fri 8:30am–4:30pm",
    tags: ["rental assistance", "eviction prevention", "housing counseling", "mental health"],
  },
  {
    name: "Habitat for Humanity — Mohawk Valley",
    category: "Housing",
    description: "Affordable homeownership program for qualifying low-income families through sweat equity builds.",
    address: "309 Rutger St, Utica, NY 13501",
    phone: "(315) 738-1833",
    website: "https://www.habitatmv.org",
    hours: "Mon–Fri 9am–5pm",
    tags: ["homeownership", "affordable housing", "repair"],
  },
  {
    name: "Oneida County Office for the Aging — HEAP",
    category: "Housing",
    description: "Home Energy Assistance Program (HEAP) for heating and utility costs. Priority for seniors and low-income households.",
    address: "800 Park Ave, Utica, NY 13501",
    phone: "(315) 798-5730",
    website: "https://www.ocgov.net/aging",
    hours: "Mon–Fri 8:30am–4:30pm",
    tags: ["HEAP", "utility assistance", "seniors", "heating"],
  },

  // HEALTHCARE
  {
    name: "Mohawk Valley Health System",
    category: "Healthcare",
    description: "Primary regional hospital system including Faxton and St. Luke's campuses. Sliding-scale financial assistance available.",
    address: "1656 Champlin Ave, Utica, NY 13502",
    phone: "(315) 624-6000",
    website: "https://www.mvhealthsystem.org",
    hours: "Emergency: 24/7 | Outpatient: varies by dept",
    tags: ["hospital", "emergency", "financial assistance", "primary care"],
  },
  {
    name: "Neighborhood Health Center",
    category: "Healthcare",
    description: "Federally Qualified Health Center (FQHC) providing primary care, dental, and behavioral health on a sliding-fee scale regardless of insurance or immigration status.",
    address: "1200 Culver Ave, Utica, NY 13502",
    phone: "(315) 624-7900",
    website: "https://www.nhcutica.org",
    hours: "Mon–Fri 8am–5pm | Extended hours available",
    tags: ["FQHC", "sliding scale", "uninsured", "dental", "primary care"],
  },
  {
    name: "Planned Parenthood — Utica Health Center",
    category: "Healthcare",
    description: "Reproductive health, STI testing, birth control, and preventive care. Accepts Medicaid and offers sliding-scale fees.",
    address: "1424 Genesee St, Utica, NY 13501",
    phone: "(315) 724-6146",
    website: "https://www.plannedparenthood.org",
    hours: "Mon–Sat — call for current hours",
    tags: ["reproductive health", "Medicaid", "STI testing"],
  },

  // REFUGEE & IMMIGRATION
  {
    name: "The Center (formerly MVRCR)",
    category: "Refugee & Immigration",
    description: "Primary refugee resettlement agency in Utica. Services include initial resettlement, employment, ESL, health access, benefits enrollment, and cultural orientation. Serves Bosnian, Somali, Burmese, and many other communities.",
    address: "201 Bleecker St, Utica, NY 13501",
    phone: "(315) 738-1083",
    website: "https://www.thecenterutica.org",
    hours: "Mon–Fri 9am–5pm",
    tags: ["refugee", "resettlement", "ESL", "immigration", "employment", "health"],
  },
  {
    name: "International Center of the Capital Region — Utica Office",
    category: "Refugee & Immigration",
    description: "Immigration legal services, citizenship preparation, and DACA renewal assistance for Utica-area immigrants.",
    address: "Utica, NY (call for current address)",
    phone: "(518) 459-6422",
    website: "https://www.internationalcenter.org",
    hours: "Mon–Fri 9am–5pm",
    tags: ["immigration", "legal", "DACA", "citizenship"],
  },
  {
    name: "Utica Public Library — New Americans Program",
    category: "Refugee & Immigration",
    description: "ESL classes, computer literacy, citizenship prep, and multilingual resources for immigrants and refugees.",
    address: "303 Genesee St, Utica, NY 13501",
    phone: "(315) 735-2279",
    website: "https://www.uticapubliclibrary.org",
    hours: "Mon–Thu 9am–8pm | Fri–Sat 9am–5pm",
    tags: ["ESL", "library", "citizenship", "multilingual", "free"],
  },

  // LEGAL AID
  {
    name: "Legal Aid Society of Mid-New York",
    category: "Legal Aid",
    description: "Free civil legal services for low-income residents: housing, family law, benefits, immigration, and consumer issues.",
    address: "255 Genesee St, Utica, NY 13501",
    phone: "(315) 732-2131",
    website: "https://www.lasmny.org",
    hours: "Mon–Fri 9am–5pm",
    tags: ["free legal", "housing", "family law", "benefits", "immigration"],
  },
  {
    name: "Oneida County Bar Association — Lawyer Referral",
    category: "Legal Aid",
    description: "Referral service connecting residents with attorneys. Low-cost initial consultations available for qualifying individuals.",
    address: "Utica, NY 13501",
    phone: "(315) 724-4982",
    website: "https://www.oneidacountybar.org",
    hours: "Mon–Fri 9am–4pm",
    tags: ["lawyer referral", "consultation", "civil", "criminal"],
  },

  // MENTAL HEALTH
  {
    name: "The Neighborhood Center — Behavioral Health Clinics",
    category: "Mental Health",
    description: "Outpatient mental health and substance use disorder treatment for children, youth, and adults. Sliding-fee scale, Medicaid accepted. Mobile Crisis Assessment Team (MCAT) available 24/7. Walk-in hours available.",
    address: "628 Mary St, Utica, NY 13501",
    phone: "(315) 272-2700",
    website: "https://www.neighborhoodctr.org/behavioral-health-care-services/clinics",
    hours: "Mon/Wed/Fri 8:30am–4:30pm | Tue/Thu 8:30am–8pm | Crisis: 24/7",
    tags: ["mental health", "substance use", "Medicaid", "crisis", "outpatient", "sliding scale"],
  },
  {
    name: "988 Suicide & Crisis Lifeline",
    category: "Mental Health",
    description: "24/7 free and confidential support for people in suicidal crisis or emotional distress. Call or text 988.",
    address: "Available anywhere by phone/text",
    phone: "988",
    website: "https://www.988lifeline.org",
    hours: "24/7",
    tags: ["crisis", "suicide", "24/7", "hotline", "free"],
  },

  // EMPLOYMENT
  {
    name: "Workforce Development Institute — Utica",
    category: "Employment",
    description: "Job training, resume assistance, and placement services. Focus on manufacturing, healthcare, and technology sectors.",
    address: "209 Elizabeth St, Utica, NY 13501",
    phone: "(315) 733-8743",
    website: "https://www.wdiny.org",
    hours: "Mon–Fri 8:30am–4:30pm",
    tags: ["job training", "resume", "placement", "workforce"],
  },
  {
    name: "NY Department of Labor — Utica Career Center",
    category: "Employment",
    description: "Unemployment insurance, job listings, résumé workshops, and career counseling. Free to all NY residents.",
    address: "207 Genesee St, Utica, NY 13501",
    phone: "(315) 793-2320",
    website: "https://dol.ny.gov",
    hours: "Mon–Fri 8:30am–4:30pm",
    tags: ["unemployment", "job search", "career counseling", "free"],
  },
  {
    name: "Mohawk Valley Community College — Workforce",
    category: "Employment",
    description: "Short-term workforce certifications, trade skills, and professional development. Financial aid available.",
    address: "1101 Sherman Dr, Utica, NY 13501",
    phone: "(315) 792-5400",
    website: "https://www.mvcc.edu/workforce",
    hours: "Mon–Fri 8am–5pm",
    tags: ["certification", "trade skills", "college", "financial aid"],
  },

  // YOUTH & FAMILY
  {
    name: "Boys & Girls Club of the Mohawk Valley",
    category: "Youth & Family",
    description: "After-school programs, summer camps, tutoring, and mentoring for youth ages 6–18. Low-cost membership.",
    address: "80 Lansing St, Utica, NY 13501",
    phone: "(315) 724-4784",
    website: "https://www.bgcmv.org",
    hours: "Mon–Fri 2pm–8pm | Summer: 7am–6pm",
    tags: ["youth", "after school", "tutoring", "summer", "mentoring"],
  },
  {
    name: "Utica City School District — Family Resource Centers",
    category: "Youth & Family",
    description: "Family support services, parent engagement, and referrals to community resources through school-based centers.",
    address: "106 Memorial Pkwy, Utica, NY 13501",
    phone: "(315) 368-6400",
    website: "https://www.uticaschools.org",
    hours: "School year hours — call for schedule",
    tags: ["school", "family support", "children", "parent resources"],
  },
  {
    name: "Oneida County DSS — Child & Family Services",
    category: "Youth & Family",
    description: "Child protective services, foster care, Medicaid enrollment, SNAP, TANF, and preventive family services.",
    address: "800 Park Ave, Utica, NY 13501",
    phone: "(315) 798-5774",
    website: "https://www.ocgov.net/dss",
    hours: "Mon–Fri 8:30am–4:30pm",
    tags: ["SNAP", "Medicaid", "TANF", "child welfare", "foster care"],
  },
];